Repository jinsuSang/east-europe-translator, pull requests merged in 2021-04, with the labels that each got.

#44 Bug/43 changes for deployment
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/healthchecker/healthchecker.controller.spec.ts
  server/src/healthchecker/healthchecker.controller.ts
  server/src/main.ts
Labels: bug

#46 enhancement: AWS setting
  client/func.js
  client/trans.html
Labels: enhancement

#47 Dev version 1.0.1
  client/func.js
  client/trans.html
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/healthchecker/healthchecker.controller.spec.ts
  server/src/healthchecker/healthchecker.controller.ts
  server/src/main.ts
Labels: enhancement

#52 bug: http request changes to https
  client/exec.js
  client/func.js
  client/trans.css
  client/trans.html
Labels: bug

#54 documentation: add version info to file names
  client/exec_v1.js
  client/func_v1.js
  client/trans_v1.css
  client/trans_v1.html
Labels: documentation

#56 documentation: add site url in README.md
  README.md
Labels: documentation

#62 bug: Prevent empty string
  client/func_v1.js
  server/package-lock.json
Labels: bug
