Repository jinsuSang/east-europe-translator, pull requests merged in 2021-03, with the labels that each got.

#7 enhancement: add global validate pipe
  server/package-lock.json
  server/package.json
  server/src/main.ts
Labels: enhancement

#8 enhancement: update js fetch api_kr
  client/trans.html
  server/package-lock.json
Labels: enhancement

#10 enhancement: create button through response in Wrap2
  client/trans.css
  client/trans.html
Labels: enhancement

#12 Enhancement/6 create server
  server/src/app.controller.ts
  server/src/app.service.ts
  server/src/config/configuration.ts
  server/src/srcTarget/source-target.ts
  server/src/translateBehavior/google-translate.ts
  server/src/translateBehavior/kakao-translate.ts
  server/src/translateBehavior/papago-translate.ts
  server/src/translator/ko-en-translator.ts
  server/src/translator/translator.ts
Labels: enhancement

#16 enhancement: limit number of characters
  client/trans.css
  client/trans.html
Labels: enhancement

#19 test: created proto endpoint test
  server/test/app.e2e-spec.ts
Labels: test

#21 enhancement:request 2nd translate
  client/trans.css
  client/trans.html
Labels: enhancement

#24 documentation: update readme.md
  README.md
  class-diagram.drawio
  class-diagram.jpg
  sequence-diagram.drawio
  sequence-diagram.jpg
Labels: documentation

#25 enhancement:organize js code
  client/exec.js
  client/func.js
  client/trans.html
Labels: enhancement

#26 enhancement: newline character to <br>
  client/func.js
Labels: enhancement

#27 enhancement: add exception log
  server/src/translateBehavior/google-translate.ts
  server/src/translateBehavior/kakao-translate.ts
  server/src/translateBehavior/papago-translate.ts
Labels: enhancement

#29 enhancement: delete button animation and fix button problem
  client/exec.js
  client/func.js
  client/trans.css
Labels: enhancement

#30 documentation:update readme.md
  README.md
Labels: documentation

#31 build: pm2 module install and set npm command
  server/package.json
Labels: build

#32 documentation: update readme.md progress status
  README.md
Labels: documentation

#33 enhancement: update footer
  client/trans.css
  client/trans.html
Labels: enhancement

#35 delete alert and update max input length
  client/func.js
  client/trans.html
Labels: enhancement

#39 enhancement: install csurf and helmet modules
  server/package-lock.json
  server/package.json
  server/src/main.ts
Labels: enhancement
